### ISSUE TITLE
Title of webpage is too long and it crashes, what can i do?

### ISSUE THREAD

**Issue by qYuki** [DrakonZZZ/Brave-rpc#5] opened 2024-09-01 00:14 UTC
C:\Users\user\OneDrive\Desktop\brave-rpc\node_modules\discord-rpc\src\client.js:178
        const e = new Error(message.data.message);
                  ^

Error: child "activity" fails because [child "state" fails because ["state" length must be less than or equal to 128 characters long]]
    at RPCClient._onRpcMessage (C:\Users\user\OneDrive\Desktop\brave-rpc\node_modules\discord-rpc\src\client.js:178:19)
    at IPCTransport.emit (node:events:520:28)
    at C:\Users\user\OneDrive\Desktop\brave-rpc\node_modules\discord-rpc\src\transports\ipc.js:138:18
    at decode (C:\Users\user\OneDrive\Desktop\brave-rpc\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (C:\Users\user\OneDrive\Desktop\brave-rpc\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (node:events:520:28)
    at emitReadable_ (node:internal/streams/readable:832:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:89:21) {
  code: 4000,
  data: {
    code: 4000,
    message: 'child "activity" fails because [child "state" fails because ["state" length must be less than or equal to 128 characters long]]'
  }
}

**Comment by DrakonZZZ** [comment] 2024-09-02 03:07
The issue is that Discord does not allow character lengths greater than 128, so it crashes the running server, but I will fix it and upload the fixed version. (Edit: bug has been fixed now)

**Closed as completed by DrakonZZZ** 2024-09-02 03:07 UTC
